version: '3'

services:

  app:
    build: ./
    depends_on:
      - postgres
    ports:
      - 8000:8000

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - 5432:5432
